### ISSUE TITLE
Procedure Entry Point not found for torchvision

### ISSUE THREAD

**Issue by Saoked** [milksense/venus#12]
When I load up venus it goes to download yolov5 and what not. Than I got a windows pop up saying this, "The procedure entry point ?get_warnAlways@Warning@c10@@YA_NXZ could not be located in the dynamic link library C:\Users\spenc\AppData\Local\Programs\Python\Python39\Lib\site-packages\torchvision\image.pyd

Than in venus cmd it says all this

[INFO] Loading the neural network model
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to C:\Users\spenc/.cache\torch\hub\master.zip
C:\Users\spenc\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: [WinError 127] The specified procedure could not be found
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "C:\Users\spenc\Downloads\venus-main (2)\venus-main\venus.py", line 73, in <module>
    main()
  File "C:\Users\spenc\Downloads\venus-main (2)\venus-main\venus.py", line 21, in main
    lunar = Aimbot(collect_data = "collect_data" in sys.argv)
  File "C:\Users\spenc\Downloads\venus-main (2)\venus-main\lib\aimbot.py", line 65, in __init__
    self.model = torch.hub.load('ultralytics/yolov5', 'custom', path='lib/best.pt', force_reload = True)
  File "C:\Users\spenc\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\hub.py", line 558, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\spenc\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\hub.py", line 587, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\spenc/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 83, in custom
    return _create(path, autoshape=autoshape, verbose=_verbose, device=device)
  File "C:\Users\spenc/.cache\torch\hub\ultralytics_yolov5_master\hubconf.py", line 33, in _create
    from models.common import AutoShape, DetectMultiBackend
  File "C:\Users\spenc/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 28, in <module>
    from utils.dataloaders import exif_transpose, letterbox
  File "C:\Users\spenc/.cache\torch\hub\ultralytics_yolov5_master\utils\dataloaders.py", line 31, in <module>
    from utils.augmentations import (Albumentations, augment_hsv, classify_albumentations, classify_transforms, copy_paste,
  File "C:\Users\spenc/.cache\torch\hub\ultralytics_yolov5_master\utils\augmentations.py", line 15, in <module>
    from utils.general import LOGGER, check_version, colorstr, resample_segments, segment2box, xywhn2xyxy
  File "C:\Users\spenc/.cache\torch\hub\ultralytics_yolov5_master\utils\general.py", line 38, in <module>
    from ultralytics.yolo.utils.checks import check_requirements
ModuleNotFoundError: No module named 'ultralytics'

**Comment by milksense** [comment]
@Saoked It looks like the problem is in your configuration.. ([similar issue](https://github.com/pyg-team/pytorch_geometric/issues/3430#issuecomment-1111526329))
